// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 73051b06cc63fbd730494da90db480932cf6120fd2b1e8914804a555bdb3a416
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BuilderPreferencesRequest](`ssz-static:"false"`)

// MarshalSSZ marshals the *BuilderPreferencesRequest to SSZ-encoded bytes.
func (t *BuilderPreferencesRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderPreferencesRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderPreferencesRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPreferencesRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Preferences'
		t := t.Preferences
		if t == nil {
			t = new(BuilderPreferences)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	// Offset Field #1 'Auth'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'Auth'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderPreferencesRequest from SSZ-encoded bytes.
func (t *BuilderPreferencesRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	{ // Field #0 'Preferences' (static)
		buf := buf[0:8]
		if t.Preferences == nil {
			t.Preferences = new(BuilderPreferences)
		}
		if err = t.Preferences.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	// Field #1 'Auth' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset1 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 12), "Auth:o")
	}
	{ // Field #1 'Auth' (dynamic)
		buf := buf[offset1:]
		if t.Auth == nil {
			t.Auth = new(SignedBuilderRequestAuth)
		}
		if err = t.Auth.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderPreferencesRequest.
func (t *BuilderPreferencesRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderPreferencesRequest)
	}
	// Field #0 'Preferences' static (8 bytes)
	// Field #1 'Auth' offset (4 bytes)
	size += 12
	{ // Dynamic field #1 'Auth'
		size += t.Auth.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderPreferencesRequest.
func (t *BuilderPreferencesRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderPreferencesRequest using the given hash walker.
func (t *BuilderPreferencesRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPreferencesRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Preferences'
		t := t.Preferences
		if t == nil {
			t = new(BuilderPreferences)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Preferences")
		}
	}
	{ // Field #1 'Auth'
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	hh.Merkleize(idx)
	return nil
}
