# golangci-lint Configuration
# 
# This configuration file defines linting rules and settings for the go-builder-client project.
# It uses golangci-lint v2 configuration format for maximum compatibility.
# 
# Official documentation: https://golangci-lint.run/usage/configuration/
# Migration guide: https://golangci-lint.run/docs/product/migration-guide
#
# Configuration sections:
# - run: Analysis execution settings (timeout, concurrency, etc.)
# - linters: Linter selection and configuration
# - settings: Individual linter settings and rules
# - exclusions: Files and patterns to exclude from linting
# - formatters: Code formatting tools and their settings

# Configuration version - must be "2" for golangci-lint v2 format
version: "2"

# Analysis execution settings
run:
  # Module download mode for dependency resolution
  # Options: readonly, vendor, mod, sum
  # readonly: Prevents automatic go.mod updates (recommended for CI)
  modules-download-mode: readonly
  
  # Include test files in analysis
  # Disabled to focus on production code quality
  tests: false
  
  # Allow multiple parallel golangci-lint instances
  # Useful for CI environments with multiple jobs
  allow-parallel-runners: true

# Linter configuration
linters:
  # Enable all available linters by default
  # This provides comprehensive code quality checks
  default: all
  
  # Disabled linters with explanations
  disable:
    - cyclop          # Disabled: Too strict cyclomatic complexity checks
    - depguard        # Disabled: Dependency management handled by go.mod
    - dupl            # Disabled: Duplicate code detection too noisy
    - err113          # Disabled: Error wrapping not always applicable
    - exhaustive      # Disabled: Enum exhaustiveness too strict
    - exhaustruct     # Disabled: Struct field initialization too strict
    - funlen          # Disabled: Function length limits too restrictive
    - gochecknoglobals # Disabled: Global variables sometimes necessary
    - gocognit        # Disabled: Cognitive complexity too strict
    - ireturn         # Disabled: Interface return types too restrictive
    - mnd             # Disabled: Magic number detection too noisy
    - perfsprint      # Disabled: Performance optimizations not always needed
    - varnamelen      # Disabled: Variable name length too strict
    - wrapcheck       # Disabled: Error wrapping not always applicable
    - wsl             # Disabled: Whitespace linting too strict (replaced with wsl_v5)
  
  # Individual linter settings and rule configurations
  settings:
    # Header comment enforcement
    goheader:
      values:
        regexp:
          # Pattern to match copyright years (supports ranges and single years)
          YEARS: (20\d\d - 20\d\d|20\d\d, 20\d\d|20\d\d)
      # Template for required file headers
      template: |-
        Copyright © {{ YEARS }} Attestant Limited.
        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    
    # Security vulnerability detection
    gosec:
      excludes:
        # G115: Deferring unsafe method on type returned from unsafe call
        # Disabled due to false positives in crypto operations
        - G115
    
    # Line length limit configuration
    lll:
      # Maximum line length (132 characters)
      # Allows for longer lines while maintaining readability
      line-length: 132
    
    # Revive linter configuration (Go linter framework)
    revive:
      # Minimum confidence level for rule violations (0.0-1.0)
      confidence: 0.8
      # Severity level for violations
      severity: error
      # Enable all available rules
      enable-all-rules: true
      # Custom rule configurations
      rules:
        - name: add-constant
          disabled: true  # Disabled: Constant extraction not always beneficial
        - name: cyclomatic
          disabled: true  # Disabled: Cyclomatic complexity handled by other linters
        - name: cognitive-complexity
          disabled: true  # Disabled: Cognitive complexity too strict
        - name: confusing-results
          # Enabled: Helps identify confusing function return patterns
        - name: function-length
          disabled: true  # Disabled: Function length limits too restrictive
        - name: line-length-limit
          arguments:
            - 132  # Maximum line length
        - name: max-public-structs
          disabled: true  # Disabled: Public struct count limits too strict
        - name: package-comments
          disabled: true  # Disabled: Package comments not always necessary
        - name: struct-tag
          arguments:
            - json,allowempty  # Required struct tags for JSON serialization
        - name: unhandled-error
          arguments:
            - fmt.Fprint   # Functions that should have error handling
            - fmt.Fprintf  # Functions that should have error handling
    
    # Static analysis checks
    staticcheck:
      checks:
        - all      # Enable all staticcheck checks
        - -ST1000  # Disable: Package naming convention (too strict)
    
    # Struct tag case enforcement
    tagliatelle:
      case:
        rules:
          json: snake  # JSON tags must use snake_case
          yaml: snake  # YAML tags must use snake_case
  
  # File and pattern exclusions
  exclusions:
    # Exclude generated files with lax matching
    generated: lax
    # Exclude common false positive patterns
    presets:
      - comments                    # Comment-related false positives
      - common-false-positives     # Common false positive patterns
      - legacy                     # Legacy code patterns
      - std-error-handling        # Standard error handling patterns
    # Specific file patterns to exclude
    paths:
      - .*_ssz\.go$    # SSZ (Simple Serialize) generated files
      - third_party$   # Third-party code directories
      - builtin$       # Built-in Go code
      - examples$      # Example code directories

# Code formatting tools
formatters:
  # Enabled formatters (applied in order)
  enable:
    - gofmt      # Standard Go formatter
    - gofumpt    # Stricter Go formatter with additional rules
    - goimports  # Import organization and formatting
  # Formatter exclusions
  exclusions:
    # Exclude generated files from formatting
    generated: lax
    # Specific file patterns to exclude from formatting
    paths:
      - .*_ssz\.go$    # SSZ generated files
      - third_party$   # Third-party code
      - builtin$       # Built-in Go code
      - examples$      # Example code