// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 661742718945ee054edb13acb343080395529c84ab844a5863f5bc135c61e144
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package fulu

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ExecutionPayloadAndBlobsBundle to SSZ-encoded bytes.
func (t *ExecutionPayloadAndBlobsBundle) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ExecutionPayloadAndBlobsBundle to SSZ-encoded bytes, appending to the provided buffer.
func (t *ExecutionPayloadAndBlobsBundle) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #1 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ExecutionPayloadAndBlobsBundle from SSZ-encoded bytes.
func (t *ExecutionPayloadAndBlobsBundle) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "ExecutionPayload:o")
	}
	// Field #1 'BlobsBundle' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(deneb.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'BlobsBundle' (dynamic)
		buf := buf[offset1:]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if err = t.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ExecutionPayloadAndBlobsBundle.
func (t *ExecutionPayloadAndBlobsBundle) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlobsBundle' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #1 'BlobsBundle'
		size += t.BlobsBundle.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ExecutionPayloadAndBlobsBundle.
func (t *ExecutionPayloadAndBlobsBundle) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *ExecutionPayloadAndBlobsBundle using the given hash walker.
func (t *ExecutionPayloadAndBlobsBundle) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadAndBlobsBundle)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	hh.Merkleize(idx)
	return nil
}
