// Code generated by fastssz. DO NOT EDIT.
// Hash: b20fd3fa36a90f0d2dfc51a0390f2c30f66d1b12329c79ff0dea63ed2849f592
// Version: 0.1.3
package fulu

import (
	apiv1 "github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SubmitBlockRequest object
func (s *SubmitBlockRequest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SubmitBlockRequest object to a target array
func (s *SubmitBlockRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(344)

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(apiv1.BidTrace)
	}
	if dst, err = s.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (1) 'ExecutionPayload'
	dst = ssz.WriteOffset(dst, offset)
	if s.ExecutionPayload == nil {
		s.ExecutionPayload = new(deneb.ExecutionPayload)
	}
	offset += s.ExecutionPayload.SizeSSZ()

	// Offset (2) 'BlobsBundle'
	dst = ssz.WriteOffset(dst, offset)
	if s.BlobsBundle == nil {
		s.BlobsBundle = new(BlobsBundle)
	}
	offset += s.BlobsBundle.SizeSSZ()

	// Offset (3) 'ExecutionRequests'
	dst = ssz.WriteOffset(dst, offset)

	// Field (4) 'Signature'
	dst = append(dst, s.Signature[:]...)

	// Field (1) 'ExecutionPayload'
	if dst, err = s.ExecutionPayload.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if dst, err = s.BlobsBundle.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	if dst, err = s.ExecutionRequests.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SubmitBlockRequest object
func (s *SubmitBlockRequest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 344 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3 uint64

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(apiv1.BidTrace)
	}
	if err = s.Message.UnmarshalSSZ(buf[0:236]); err != nil {
		return err
	}

	// Offset (1) 'ExecutionPayload'
	if o1 = ssz.ReadOffset(buf[236:240]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 344 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'BlobsBundle'
	if o2 = ssz.ReadOffset(buf[240:244]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'ExecutionRequests'
	if o3 = ssz.ReadOffset(buf[244:248]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Field (4) 'Signature'
	copy(s.Signature[:], buf[248:344])

	// Field (1) 'ExecutionPayload'
	{
		buf = tail[o1:o2]
		if s.ExecutionPayload == nil {
			s.ExecutionPayload = new(deneb.ExecutionPayload)
		}
		if err = s.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (2) 'BlobsBundle'
	{
		buf = tail[o2:o3]
		if s.BlobsBundle == nil {
			s.BlobsBundle = new(BlobsBundle)
		}
		if err = s.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (3) 'ExecutionRequests'
	{
		buf = tail[o3:]
		if s.ExecutionRequests == nil {
			s.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = s.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SubmitBlockRequest object
func (s *SubmitBlockRequest) SizeSSZ() (size int) {
	size = 344

	// Field (1) 'ExecutionPayload'
	if s.ExecutionPayload == nil {
		s.ExecutionPayload = new(deneb.ExecutionPayload)
	}
	size += s.ExecutionPayload.SizeSSZ()

	// Field (2) 'BlobsBundle'
	if s.BlobsBundle == nil {
		s.BlobsBundle = new(BlobsBundle)
	}
	size += s.BlobsBundle.SizeSSZ()

	// Field (3) 'ExecutionRequests'
	if s.ExecutionRequests == nil {
		s.ExecutionRequests = new(electra.ExecutionRequests)
	}
	size += s.ExecutionRequests.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the SubmitBlockRequest object
func (s *SubmitBlockRequest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SubmitBlockRequest object with a hasher
func (s *SubmitBlockRequest) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if s.Message == nil {
		s.Message = new(apiv1.BidTrace)
	}
	if err = s.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'ExecutionPayload'
	if err = s.ExecutionPayload.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'BlobsBundle'
	if err = s.BlobsBundle.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'ExecutionRequests'
	if err = s.ExecutionRequests.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'Signature'
	hh.PutBytes(s.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SubmitBlockRequest object
func (s *SubmitBlockRequest) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
