// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fa67aaf7fc65702aa775b204cc5192980c98d0e6e502defcec90314cc362c74f
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package v1

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *SignedValidatorRegistrations to SSZ-encoded bytes.
func (t *SignedValidatorRegistrations) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedValidatorRegistrations to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedValidatorRegistrations) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	dstlen := len(dst)
	// Offset Field #0 'Registrations'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Registrations'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Registrations
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Registrations")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedValidatorRegistrations from SSZ-encoded bytes.
func (t *SignedValidatorRegistrations) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'Registrations' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "Registrations:o")
	}
	{ // Field #0 'Registrations' (dynamic)
		buf := buf[offset0:]
		val1 := t.Registrations
		itemCount := len(buf) / 180
		if len(buf)%180 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 180), "Registrations")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Registrations")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(SignedValidatorRegistration)
			}
			buf := buf[180*idx1 : 180*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
		}
		t.Registrations = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedValidatorRegistrations.
func (t *SignedValidatorRegistrations) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	// Field #0 'Registrations' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'Registrations'
		size += len(t.Registrations) * 180
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedValidatorRegistrations.
func (t *SignedValidatorRegistrations) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *SignedValidatorRegistrations using the given hash walker.
func (t *SignedValidatorRegistrations) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Registrations'
		t := t.Registrations
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Registrations")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
