// Code generated by fastssz. DO NOT EDIT.
// Hash: 1edb7a9deff24711a3d33b2f56623cb6cf5dc5a8ac5b4e7bb68df865923ce099
// Version: 0.1.4
package v1

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the SignedValidatorRegistrationList object
func (s *SignedValidatorRegistrationList) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the SignedValidatorRegistrationList object to a target array
func (s *SignedValidatorRegistrationList) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'Items'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'Items'
	if size := len(s.Items); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("SignedValidatorRegistrationList.Items", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(s.Items); ii++ {
		if dst, err = s.Items[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the SignedValidatorRegistrationList object
func (s *SignedValidatorRegistrationList) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Items'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'Items'
	{
		buf = tail[o0:]
		num, err := ssz.DivideInt2(len(buf), 180, 1099511627776)
		if err != nil {
			return err
		}
		s.Items = make([]*SignedValidatorRegistration, num)
		for ii := 0; ii < num; ii++ {
			if s.Items[ii] == nil {
				s.Items[ii] = new(SignedValidatorRegistration)
			}
			if err = s.Items[ii].UnmarshalSSZ(buf[ii*180 : (ii+1)*180]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the SignedValidatorRegistrationList object
func (s *SignedValidatorRegistrationList) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'Items'
	size += len(s.Items) * 180

	return
}

// HashTreeRoot ssz hashes the SignedValidatorRegistrationList object
func (s *SignedValidatorRegistrationList) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the SignedValidatorRegistrationList object with a hasher
func (s *SignedValidatorRegistrationList) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Items'
	{
		subIndx := hh.Index()
		num := uint64(len(s.Items))
		if num > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range s.Items {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1099511627776)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the SignedValidatorRegistrationList object
func (s *SignedValidatorRegistrationList) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
