// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fa67aaf7fc65702aa775b204cc5192980c98d0e6e502defcec90314cc362c74f
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
//
// NOTE: the Marshal/Unmarshal/Size methods for SignedValidatorRegistrations are
// hand-adjusted to encode the type as a bare list of registrations *without* the
// leading 4-byte offset that dynssz would otherwise emit for a container holding a
// single variable-length field.
// This is non-standard, but required for conformance with
// https://ethereum.github.io/builder-specs/#/Builder/registerValidator
// which presents the list as a simple array rather than an object.
// See https://eth2book.info/capella/part2/building_blocks/ssz/#lists for details.
// If this file is regenerated, re-apply these adjustments (or exclude the type from
// generation in generate.go).
package v1

import (
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[SignedValidatorRegistrations](`ssz-static:"false"`)

// MarshalSSZ marshals the *SignedValidatorRegistrations to SSZ-encoded bytes.
func (t *SignedValidatorRegistrations) MarshalSSZ() ([]byte, error) {
	return t.MarshalSSZTo(nil)
}

// MarshalSSZTo marshals the *SignedValidatorRegistrations to SSZ-encoded bytes, appending to the provided buffer.
// Note that this does not marshal an offset, just the elements of the list (see the file header for details).
func (t *SignedValidatorRegistrations) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	{ // Dynamic Field #0 'Registrations'
		t := t.Registrations
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Registrations")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedValidatorRegistrations from SSZ-encoded bytes.
// Note that this expects the encoded bytes to be a bare list, without a leading offset (see the file header for details).
func (t *SignedValidatorRegistrations) UnmarshalSSZ(buf []byte) (err error) {
	{ // Field #0 'Registrations' (dynamic)
		val1 := t.Registrations
		itemCount := len(buf) / 180
		if len(buf)%180 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 180), "Registrations")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Registrations")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(SignedValidatorRegistration)
			}
			buf := buf[180*idx1 : 180*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
		}
		t.Registrations = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedValidatorRegistrations.
func (t *SignedValidatorRegistrations) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	{ // Dynamic field #0 'Registrations'
		size += len(t.Registrations) * 180
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedValidatorRegistrations.
func (t *SignedValidatorRegistrations) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedValidatorRegistrations using the given hash walker.
func (t *SignedValidatorRegistrations) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedValidatorRegistrations)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Registrations'
		t := t.Registrations
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Registrations")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(SignedValidatorRegistration)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Registrations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
