// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 90e0ae80d5714d80b3c6f5420710047c78d88cd57f2531191b8e75d276c499ea
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BuilderBid](`ssz-static:"false"`)

// MarshalSSZ marshals the *BuilderBid to SSZ-encoded bytes.
func (t *BuilderBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderBid to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #2 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(capella.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Header")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderBid from SSZ-encoded bytes.
func (t *BuilderBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 84), "Header:o")
	}
	{ // Field #1 'Value' (static)
		buf := buf[4:36]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #2 'Pubkey' (static)
		buf := buf[36:84]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:]
		if t.Header == nil {
			t.Header = new(capella.ExecutionPayloadHeader)
		}
		if err = t.Header.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Header")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderBid.
func (t *BuilderBid) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'Value' static (32 bytes)
	// Field #2 'Pubkey' static (48 bytes)
	size += 84
	{ // Dynamic field #0 'Header'
		size += t.Header.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderBid.
func (t *BuilderBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderBid using the given hash walker.
func (t *BuilderBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(capella.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Header")
		}
	}
	{ // Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val1, val1Empty uint64
		for idx1 := range 4 {
			if idx1 < 4 {
				val1 = (*t)[idx1]
			} else if idx1 == 4 {
				val1 = val1Empty
			}
			hh.AppendUint64(val1)
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	{ // Field #2 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
