// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 33d88ef16b1c9e6d96335ac5dca30742e620bf5a1f287fa77962115ebb59565f
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package capella

import (
	"encoding/binary"

	"github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/capella"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[SubmitBlockRequest](`ssz-static:"false"`)

// MarshalSSZ marshals the *SubmitBlockRequest to SSZ-encoded bytes.
func (t *SubmitBlockRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SubmitBlockRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *SubmitBlockRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	// Offset Field #1 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #2 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #1 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen+236:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(capella.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SubmitBlockRequest from SSZ-encoded bytes.
func (t *SubmitBlockRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 336 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 336)
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:236]
		if t.Message == nil {
			t.Message = new(v1.BidTrace)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	// Field #1 'ExecutionPayload' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[236:240]))
	if offset1 != 336 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 336), "ExecutionPayload:o")
	}
	{ // Field #2 'Signature' (static)
		buf := buf[240:336]
		copy(t.Signature[:], buf)
	}
	{ // Field #1 'ExecutionPayload' (dynamic)
		buf := buf[offset1:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(capella.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SubmitBlockRequest.
func (t *SubmitBlockRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	// Field #0 'Message' static (236 bytes)
	// Field #1 'ExecutionPayload' offset (4 bytes)
	// Field #2 'Signature' static (96 bytes)
	size += 336
	{ // Dynamic field #1 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SubmitBlockRequest.
func (t *SubmitBlockRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SubmitBlockRequest using the given hash walker.
func (t *SubmitBlockRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(capella.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #2 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
