// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b7889288072c895880b042595d9757aba0df3ba806effa251340e2b911d7e269
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package deneb

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BlobsBundle to SSZ-encoded bytes.
func (t *BlobsBundle) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BlobsBundle to SSZ-encoded bytes, appending to the provided buffer.
func (t *BlobsBundle) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlobsBundle)
	}
	dstlen := len(dst)
	// Offset Field #0 'Commitments'
	// Offset Field #1 'Proofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Commitments'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Commitments
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Commitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Proofs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #2 'Blobs'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Blobs
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Blobs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:131072]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BlobsBundle from SSZ-encoded bytes.
func (t *BlobsBundle) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'Commitments' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Commitments:o")
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Proofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Commitments' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Commitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Commitments")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "Commitments")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.Commitments = val1
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.Proofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Proofs")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "Proofs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.Proofs = val2
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val3 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "Blobs")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			buf := buf[131072*idx1 : 131072*(idx1+1)]
			copy(val3[idx1][:], buf)
		}
		t.Blobs = val3
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BlobsBundle.
func (t *BlobsBundle) SizeSSZ() (size int) {
	if t == nil {
		t = new(BlobsBundle)
	}
	// Field #0 'Commitments' offset (4 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Commitments'
		size += len(t.Commitments) * 48
	}
	{ // Dynamic field #1 'Proofs'
		size += len(t.Proofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BlobsBundle.
func (t *BlobsBundle) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *BlobsBundle using the given hash walker.
func (t *BlobsBundle) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlobsBundle)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Commitments'
		t := t.Commitments
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Commitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
