// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 01a6ea7264b38339a5403cc97ae4bdc3f543893e9fc42ce88edc8dde05ae7c71
// Version: v1.3.0 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BuilderBid to SSZ-encoded bytes.
func (t *BuilderBid) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderBid to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderBid) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	// Offset Field #1 'BlobKZGCommitments'
	// Offset Field #2 'ExecutionRequests'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #4 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Header")
		}
	}
	{ // Dynamic Field #1 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "BlobKZGCommitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #2 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderBid from SSZ-encoded bytes.
func (t *BuilderBid) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 92 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 92)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 92 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 92), "Header:o")
	}
	// Field #1 'BlobKZGCommitments' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "BlobKZGCommitments:o")
	}
	// Field #2 'ExecutionRequests' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "ExecutionRequests:o")
	}
	{ // Field #3 'Value' (static)
		buf := buf[12:44]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #4 'Pubkey' (static)
		buf := buf[44:92]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:offset1]
		if t.Header == nil {
			t.Header = new(deneb.ExecutionPayloadHeader)
		}
		if err = t.Header.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Header")
		}
	}
	{ // Field #1 'BlobKZGCommitments' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BlobKZGCommitments")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "BlobKZGCommitments")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.BlobKZGCommitments = val2
	}
	{ // Field #2 'ExecutionRequests' (dynamic)
		buf := buf[offset2:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = t.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderBid.
func (t *BuilderBid) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'BlobKZGCommitments' offset (4 bytes)
	// Field #2 'ExecutionRequests' offset (4 bytes)
	// Field #3 'Value' static (32 bytes)
	// Field #4 'Pubkey' static (48 bytes)
	size += 92
	{ // Dynamic field #0 'Header'
		size += t.Header.SizeSSZ()
	}
	{ // Dynamic field #1 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	{ // Dynamic field #2 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderBid.
func (t *BuilderBid) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *BuilderBid using the given hash walker.
func (t *BuilderBid) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Header")
		}
	}
	{ // Field #1 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "BlobKZGCommitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	{ // Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val1, val1Empty uint64
		for idx1 := range 4 {
			if idx1 < 4 {
				val1 = (*t)[idx1]
			} else if idx1 == 4 {
				val1 = val1Empty
			}
			hh.AppendUint64(val1)
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	{ // Field #4 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
