// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6ed76dd62257573a0314e578ed2202bbc4f09814e44e6bb0f1a81a7af5e6e254
// Version: v1.2.2 (https://github.com/pk910/dynamic-ssz)
package electra

import (
	"encoding/binary"

	deneb1 "github.com/attestantio/go-builder-client/api/deneb"
	"github.com/attestantio/go-builder-client/api/v1"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/electra"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *SubmitBlockRequest to SSZ-encoded bytes.
func (t *SubmitBlockRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SubmitBlockRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *SubmitBlockRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	// Offset Field #1 'ExecutionPayload'
	// Offset Field #2 'BlobsBundle'
	// Offset Field #3 'ExecutionRequests'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #4 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #1 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen+236:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+240:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(deneb1.BlobsBundle)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Dynamic Field #3 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+244:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SubmitBlockRequest from SSZ-encoded bytes.
func (t *SubmitBlockRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 344 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 344)
	}
	{ // Field #0 'Message' (static)
		buf := buf[0:236]
		if t.Message == nil {
			t.Message = new(v1.BidTrace)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	// Field #1 'ExecutionPayload' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[236:240]))
	if offset1 != 344 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 344), "ExecutionPayload:o")
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[240:244]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "BlobsBundle:o")
	}
	// Field #3 'ExecutionRequests' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[244:248]))
	if offset3 < offset2 || offset3 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset2, buflen), "ExecutionRequests:o")
	}
	{ // Field #4 'Signature' (static)
		buf := buf[248:344]
		copy(t.Signature[:], buf)
	}
	{ // Field #1 'ExecutionPayload' (dynamic)
		buf := buf[offset1:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(deneb.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:offset3]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(deneb1.BlobsBundle)
		}
		if err = t.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Field #3 'ExecutionRequests' (dynamic)
		buf := buf[offset3:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(electra.ExecutionRequests)
		}
		if err = t.ExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SubmitBlockRequest.
func (t *SubmitBlockRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	// Field #0 'Message' static (236 bytes)
	// Field #1 'ExecutionPayload' offset (4 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ExecutionRequests' offset (4 bytes)
	// Field #4 'Signature' static (96 bytes)
	size += 344
	{ // Dynamic field #1 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #2 'BlobsBundle'
		size += t.BlobsBundle.SizeSSZ()
	}
	{ // Dynamic field #3 'ExecutionRequests'
		size += t.ExecutionRequests.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SubmitBlockRequest.
func (t *SubmitBlockRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
// HashTreeRootWith computes the SSZ hash tree root of the *SubmitBlockRequest using the given hash walker.
func (t *SubmitBlockRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SubmitBlockRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(v1.BidTrace)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(deneb.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(deneb1.BlobsBundle)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(electra.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionRequests")
		}
	}
	{ // Field #4 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
